CC = gcc
CXX = g++
CFLAGS = -Wall -I.
CXXFLAGS = -Wall
SRC_STACK = stack.c
SRC_QUEUE = queue.c
SRC_LIST = list.cpp
SRC_BINARYTREE = binaryTree.c
TARGET_STACK = stack.exe
TARGET_QUEUE = queue.exe
TARGET_LIST = list.exe
TARGET_BINARYTREE = binaryTree.exe

all: $(TARGET_STACK) $(TARGET_QUEUE) $(TARGET_LIST) $(TARGET_BINARYTREE)

$(TARGET_STACK): $(SRC_STACK)
	$(CC) $(CFLAGS) -o $(TARGET_STACK) $(SRC_STACK)

$(TARGET_QUEUE): $(SRC_QUEUE)
	$(CC) $(CFLAGS) -o $(TARGET_QUEUE) $(SRC_QUEUE)

$(TARGET_BINARYTREE): $(SRC_BINARYTREE)
	$(CC) $(CFLAGS) -o $(TARGET_BINARYTREE) $(SRC_BINARYTREE)
	
$(TARGET_LIST): $(SRC_LIST)
	$(CXX) $(CXXFLAGS) -o $(TARGET_LIST) $(SRC_LIST)

clean:
	rm -f $(TARGET_STACK) $(TARGET_QUEUE) $(TARGET_LIST) $(TARGET_BINARYTREE)